# Generated by Django 5.1.4 on 2024-12-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
